#!/bin/sh

program="$1"
choice="$2"

for h in 1 5 10 30 60 100; do
	h=$(echo "scale = 4; $h / 1000" | bc -l)
	echo "Solution of SHM" >> "0$h.dat"
	echo "Step Size = $h RK4 Method" >> "0$h.dat"
	printf "Time\ty\tv\tΔy\tΔv\n"  >> "0$h.dat"
	"$program" "$h" "$choice" \
		| awk '{printf( "%f\t%f\t%f\t%f\t%f\n", $1, $2, $3, cos(2*$1) - $2, -2 * sin(2*$1) - $3)}'\
			>> "0$h.dat"
done
